### ISSUE TITLE
Cannot compile on Ubuntu 24.04

### ISSUE THREAD

**Issue by ProfFan** [pkts-rs/tappers#38]
```
index.crates.io-6f17d22bba15001f/tappers-0.4.1/src/linux/tap.rs:157:23
    |
157 |             ifr_name: old_if_name.name_raw_i8(),
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `[u8; 16]`, found `[i8; 16]`
    |
    = note: expected array `[u8; 16]`
               found array `[i8; 16]`
```

Seems that the expected type in libc::ifreq is u8

**Comment by nathaniel-bennett** [comment]
I see what the issue is--I mistakenly assumed `libc::c_char` was an `i8` type across all architectures when it's `u8` for arm. I'll get that fixed right away 👍

**Comment by nathaniel-bennett** [comment]
Could you verify that the #39 has fixed the issue? Just temporarily change your Cargo.toml dependency to be:
```toml
tappers = { version = "0.4.1", git = "https://github.com/pkts-rs/tappers.git" }
```

If it compiles, I'll go ahead and bump the version to 0.4.2 so that you can use the usual crates.io dependency

**Comment by ProfFan** [comment]
@nathaniel-bennett Still fails:

```
warning: `tokio-smoltcp` (lib) generated 1 warning (run `cargo fix --lib -p tokio-smoltcp` to apply 1 suggestion)
error[E0308]: mismatched types
  --> /home/fan/.cargo/git/checkouts/tappers-36ad9e90d196c018/6d88bcb/src/linux/tap.rs:46:24
   |
46 |             ifr_name: [0i8; 16],
   |                        ^^^ expected `u8`, found `i8`
   |
help: change the type of the numeric literal from `i8` to `u8`
   |
46 |             ifr_name: [0u8; 16],
   |                         ~~

error[E0308]: mismatched types
   --> /home/fan/.cargo/git/checkouts/tappers-36ad9e90d196c018/6d88bcb/src/linux/tap.rs:140:24
    |
140 |             ifr_name: [0i8; 16],
    |                        ^^^ expected `u8`, found `i8`
    |
help: change the type of the numeric literal from `i8` to `u8`
    |
140 |             ifr_name: [0u8; 16],
    |                         ~~

error[E0308]: mismatched types
   --> /home/fan/.cargo/git/checkouts/tappers-36ad9e90d196c018/6d88bcb/src/linux/tap.rs:180:24
    |
180 |             ifr_name: [0i8; 16],
    |                        ^^^ expected `u8`, found `i8`
    |
help: change the type of the numeric literal from `i8` to `u8`
    |
180 |             ifr_name: [0u8; 16],
    |                         ~~

error[E0308]: mismatched types
   --> /home/fan/.cargo/git/checkouts/tappers-36ad9e90d196c018/6d88bcb/src/linux/tap.rs:201:24
    |
201 |             ifr_name: [0i8; 16],
    |                        ^^^ expected `u8`, found `i8`
    |
help: change the type of the numeric literal from `i8` to `u8`
    |
201 |             ifr_name: [0u8; 16],
    |                         ~~

error[E0308]: mismatched types
  --> /home/fan/.cargo/git/checkouts/tappers-36ad9e90d196c018/6d88bcb/src/linux/tun.rs:46:24
   |
46 |             ifr_name: [0i8; 16],
   |                        ^^^ expected `u8`, found `i8`
   |
help: change the type of the numeric literal from `i8` to `u8`
   |
46 |             ifr_name: [0u8; 16],
   |                         ~~

error[E0308]: mismatched types
   --> /home/fan/.cargo/git/checkouts/tappers-36ad9e90d196c018/6d88bcb/src/linux/tun.rs:137:24
    |
137 |             ifr_name: [0i8; 16],
    |                        ^^^ expected `u8`, found `i8`
    |
help: change the type of the numeric literal from `i8` to `u8`
    |
137 |             ifr_name: [0u8; 16],
    |                         ~~

error[E0308]: mismatched types
   --> /home/fan/.cargo/git/checkouts/tappers-36ad9e90d196c018/6d88bcb/src/linux/tun.rs:178:24
    |
178 |             ifr_name: [0i8; 16],
    |                        ^^^ expected `u8`, found `i8`
    |
help: change the type of the numeric literal from `i8` to `u8`
    |
178 |             ifr_name: [0u8; 16],
    |                         ~~

error[E0308]: mismatched types
   --> /home/fan/.cargo/git/checkouts/tappers-36ad9e90d196c018/6d88bcb/src/linux/tun.rs:199:24
    |
199 |             ifr_name: [0i8; 16],
    |                        ^^^ expected `u8`, found `i8`
    |
help: change the type of the numeric literal from `i8` to `u8`
    |
199 |             ifr_name: [0u8; 16],
    |                         ~~

error[E0308]: mismatched types
    --> /home/fan/.cargo/git/checkouts/tappers-36ad9e90d196c018/6d88bcb/src/lib.rs:678:55
     |
678  |         match unsafe { libc::if_indextoname(if_index, name.as_mut_ptr() as *mut i8) } {
     |                        --------------------           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `*mut u8`, found `*mut i8`
     |                        |
     |                        arguments to this function are incorrect
     |
     = note: expected raw pointer `*mut u8`
                found raw pointer `*mut i8`
note: function defined here
    --> /home/fan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.161/src/unix/mod.rs:1039:12
     |
1039 |     pub fn if_indextoname(ifindex: ::c_uint, ifname: *mut ::c_char) -> *mut ::c_char;
```

**Comment by nathaniel-bennett** [comment]
I've gone through every instance of `i8` now and replaced with `libc::c_char` now--these were some of the ones I missed. I've pushed these fixes to the main branch, so hopefully it all works properly!

**Comment by nathaniel-bennett** [comment]
I'll try to see what I can do to get a CI image for arm integrated so that this doesn't regress in the future

**Comment by nathaniel-bennett** [comment]
Alright, CI for arm on Linux is now applied and I fixed the remaining issues that cropped up as a result of having that enabled. I've pushed v0.4.2--let me know if it doesn't compile properly for you, otherwise I'll consider this issue closed :+1:

**Comment by ProfFan** [comment]
Everything works on my local ARM computer, thank you very much :)
